org.gradle.jvmargs=-Xmx4G

# Gradle Properties
mavenGroup=example.example
customArchivesBaseName=Example

# Mod Properties
# For edit other properties, edit "fabric.mod.json" and "mod.toml"
# modid, description, authors, icon, displayUrl, credits, updateJSONURL
modName=Example
modLicense=MIT
modVersion=1.0.0
modIssueTracker=https://github.com/Example/Example/issues
modAuthor=Example
modDescription=Example for create mods on Architectury.

# Dependencies OPTIONAL
fabricApiVersion=0.154.2

# Minecraft Properties
minecraftVersion=26.2

# Fabric Properties
fabricLoaderVersion=0.19.3
fabricLoaderRange=>=0.18.0
fabricMinecraftVersionRange=>=26.2

# NeoForge Properties
neoforgeVersion=26.2.0.9-beta
neoforgeLoaderRange=[26.2,)
neoforgeMinecraftVersionRange=[26.2]